### ISSUE TITLE
OpenCart v3.x

### ISSUE THREAD

**Issue by Vija02** [veritrans/SNAP-Opencart#16]
Any plans to support OpenCart v3.x?

**Comment by harrypujianto** [comment]
there's a plan to support oc v3.x. maybe on another branch or diffrent repo. it's been on the pipeline already

**Comment by harrypujianto** [comment]
Hi there, just incase you haven't create the oc3 module.. still on my github, please try it on..
https://github.com/harrypujianto/SNAP-Opencart3
