### ISSUE TITLE
Field2 ini kegunaannya apa saja ya?

### ISSUE THREAD

**Issue by handoyo** [veritrans/SNAP-Opencart#18]
![midtrans](https://user-images.githubusercontent.com/225439/30849201-c41b78b4-a2cb-11e7-870a-101b81fae208.png)

**Comment by harrypujianto** [comment]
one click ini jika dienable dan ada MID recurring, maka ketika buka snap berikutnya dengan customer details yang sama maka pembayaran kartu kredit hanya tinggal klik 1 button saja, tidak ada 3ds

untuk custom field silahkan dilihat disini
https://api-docs.midtrans.com/#charge-features

**Comment by handoyo** [comment]
Baik, makasih atas penjelasannya.
