### ISSUE TITLE
Kompatibilitas dengan OC v2.3.x.x

### ISSUE THREAD

**Issue by azharp** [veritrans/SNAP-Opencart#21]
Halo,

Untuk OC v2.3 versi mana yang sebaiknya dipakai?
Apakah versi ini atau versi lain pada link berikut (https://github.com/harrypujianto/SNAP-Opencart-2.3) karena saya lihat versi ini lebih terupdate.

Terima kasih.

**Comment by harrypujianto** [comment]
Silahkan gunakan yang ada di link tersebut untuk oc versi 2.3. yang ada di repo ini hanya 2.0-2.2
