### ISSUE TITLE
Snap tampil tapi tidak memproses data

### ISSUE THREAD

**Issue by jimmydac** [veritrans/SNAP-Opencart#25]
Mas/Om
saya menggunakan OC 2.1.02 , konfigurasi sudah sesuai panduan menggunakan 'Production' serta key dan ID nya sdh sesuai,..namun yang keluar SNAP dengan tulisan pesan "Kami tidak menemukan transaksi Anda

Transaksi Anda tidak tersedia, atau URL yang Anda masukkan salah."

apa yang salah ya,..mhn panduannya.

**Comment by carolus10benny** [comment]
Hi @jimmydac Untuk errornya di atas banyak faktor yang menyebabkan error tersebut. Biasanya terkait dengan URL dan juga Credential Keys yang digunakan tidak sesuai. Jika berkenan bisa langsung mengirimkan data order dan juga error detailnya ke support@midtrans.com agar bisa diinvestige lebih detail. Thanks in advance.

**Comment by fajaruddinmeilana** [comment]
Saat popup snap terbuka dan menampilkan error seperti itu coba anda inspect elemen dan tab console maka disitu akan terlihat errornya

**Comment by jauharibill** [comment]
> Saat popup snap terbuka dan menampilkan error seperti itu coba anda inspect elemen dan tab console maka disitu akan terlihat errornya

solutif. kalo di saya ini karna url sandbox di snap.js belom di ganti ke production. 
sandbox : https://app.sandbox.midtrans.com/snap/snap.js
prod : https://app.midtrans.com/snap/snap.js

**Comment by gerrnp** [comment]
> 
> 
> Saat popup snap terbuka dan menampilkan error seperti itu coba anda inspect elemen dan tab console maka disitu akan terlihat errornya

**Uncaught TypeError: t is null**
Nah Kalo ini knapa ya mass?

**Comment by muhzulzidan** [comment]
kok gua merasa aneh baca indo di github yah:D

**Comment by joglomedia** [comment]
> kok gua merasa aneh baca indo di github yah:D

aneh kenapa pak? :/

**Comment by kasfulanwar** [comment]
Permisi min, mohon error ini diperbaiki,

jadi saya mengalami kendala yang sama, dan terselesaikan dengan melakukan hal berikut :
- rubah nama controller "snap" menjadi "**Snap**" (perhatikan huruf besarnya)
- rubah nama controller "notification menjadi "**Notification**"

karena controller codeigniter mengharuskan huruf capital
